FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install -y \
        ruby \
        ruby-dev \
        rubygems \
        build-essential \
        git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN gem install --no-document fpm

WORKDIR /work

CMD ["/bin/bash"]
